---
- name: Install i3
  pacman: name={{ item }} state=present
  with_items:
      - i3-wm
      - i3blocks
      - i3lock
      - i3status

- name: Install rofi
  pacman: name=rofi state=present
  tags:
    - rofi
