---
- name: Install NetworkManager and dependencies
  pacman: name={{ item }} state=present
  with_items:
      - networkmanager
      - networkmanager-openvpn
      - network-manager-applet

- name: Enable and start NetworkManager
  service: name=NetworkManager.service enabled=yes state=started
